title: el's techwriting portfolio
description: a glimpse into my experience capturing tech into digestable content
lsi: false
safe: true
remote_theme: pages-themes/leap-day@v0.2.0
show_downloads: false
plugins:
  - jekyll-remote-theme
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  input: GFM
